apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: guestbook
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guestbook
    spec:
      containers:
      - image: ibmcom/guestbook:v2
        imagePullPolicy: Never
        name: guestbook
        resources: {}
        ports:
          - containerPort: 3000
        env:
        - name: NAME
          valueFrom:
           configMapKeyRef:
            name: guestbook-cm
            key: name
        - name: REDIS_MASTER_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              name: guestbook-secrets
              key: guestbookhost
        - name: REDIS_MASTER_SERVICE_PORT
          valueFrom:
            secretKeyRef:
              name: guestbook-secrets
              key: guestbookport
        - name: REDIS_MASTER_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: guestbook-secrets
              key: guestbookpass
        - name: REDIS_MASTER_PORT
          valueFrom:
            secretKeyRef:
              name: guestbook-secrets
              key: guestbookmasterport

status: {}
